name: testing for the first time
on: workflow_dispatch
jobs:   
    Task1:
        runs-on: ubuntu-latest
        steps:
            - name: get code
              uses: actions/checkout@v3
            - name: Instal nodejs
              uses: actions/setup-node@v3
              with:
                node-version:   18
            - name: install dependencies
              run: npm ci
            - name: Run tests
              run:  npm test  