name: testing for the first time
on: workflow_dispatch
jobs:   
    Task1:
        runs-on: ubuntu-latest
        steps:
            - name: update packagaes
              run: sudo apt upgrade
              